### ISSUE TITLE
Error while instantiating a Command

### ISSUE THREAD

**Issue by massimilianobraglia** [jymfony/jymfony#7]
Once declared as a service a Command (obviously an extension of `Jymfony.Component.Console.Command.Command`) and tried to retrieve the command from `Container::get('my_command_id')`, the following exception is thrown.

```
LogicException: Command class "Jymfony.Component.Console.Command.Command" is not correctly initialized. You probably forgot to call the parent constructor.
```

It seems that base javascript `constructor` is not called.

**Comment by alekitto** [comment]
Please write here the service definition or a failing test.

**Comment by massimilianobraglia** [comment]
```
container.register('command_1', 'MyCommand')
    .setPublic(true)
    .setFile(`${path.dirname(require.main.filename)}/src/Bundle/FrameworkBundle/fixtures/MyCommand.js`)
;
```

I had to extend `JsFileLoader::load` context variable with `path` and `require` in order to get the complete path to my Command

**Comment by alekitto** [comment]
`MyCommand` class is outside of the autoloader namespaces.
`__construct` method should be called in order for this command to work.

**Comment by massimilianobraglia** [comment]
thank you!
